export type ThemeMode = 'light' | 'dark' | 'system';
export type FeedDensity = 'comfortable' | 'standard' | 'compact';
export type ImageQuality = 'standard' | 'hd' | 'raw';
export type AccentColor = 'green' | 'blue' | 'violet' | 'orange';
export type CommentSort = 'hot' | 'latest';
export type HomeTabKey = 'index_v8' | 'digest' | 'hot' | 'latest' | 'cool_picture' | 'secondhand';
export type ExternalLinkMode = 'internal' | 'system';
export type TimeDisplayMode = 'relative' | 'absolute';
export type UpdateChannel = 'stable' | 'beta';

export interface NavVisibilitySettings {
  home: boolean;
  feeds: boolean;
  discover: boolean;
  apps: boolean;
  games: boolean;
  topics: boolean;
  reviews: boolean;
  secondhand: boolean;
  notifications: boolean;
  favorites: boolean;
  history: boolean;
  messages: boolean;
  following: boolean;
}

export interface AppSettings {
  theme: ThemeMode;
  density: FeedDensity;
  fontSize: number;
  zoom: number;
  zoomManuallySet: boolean;
  sidebarCollapsed: boolean;
  reduceMotion: boolean;
  inlineComments: boolean;
  accentColor: AccentColor;
  collapseLines: number;
  commentSort: CommentSort;
  infiniteScroll: boolean;
  autoPlayGif: boolean;
  showDeviceInfo: boolean;
  defaultHomeTab: HomeTabKey;
  downloadPath: string;
  maxConcurrentDownloads: number;
  autoCleanCache: boolean;
  cacheThresholdMB: number;
  imageQuality: ImageQuality;
  navVisibility?: NavVisibilitySettings;
  checkUpdateOnStartup: boolean;
  ignoredUpdateVersion: string;
  ignoreAllUpdates: boolean;
  closeToTray: boolean;
  autostart: boolean;
  startMinimized: boolean;
  alwaysOnTop: boolean;
  rememberWindowState: boolean;
  notifyReplies: boolean;
  notifyAt: boolean;
  notifyPm: boolean;
  desktopNotifications: boolean;
  notificationSound: boolean;
  notificationPollInterval: number;
  externalLinkMode: ExternalLinkMode;
  timeDisplay: TimeDisplayMode;
  hideAdCards: boolean;
  blockedKeywords: string[];
  publishDeviceSignature: boolean;
  deviceSignature: string;
  imageOpenMode: ExternalLinkMode;
  updateSpeedLimitKBps: number;
  proxyUrl: string;
  notifyDownloadComplete: boolean;
  updateChannel: UpdateChannel;
  experimentalFeatures: boolean;
}
